# training configs
status: train
# status: test
# name: TCLNET
name: TYLNet_simam
train_batch_size: 32
test_batch_size: 1
gpu_ids: 0
test_epoch: 20
epoch: 100
scheduler_epoch: [15,30]
gamma: 0.1
resume_epoch: 0
learning_rate: 0.001
attention_module: simam  # options: baseline, baseline_skip, se, skattention, cbam, resblock+cbam, ca, eca, simam
use_skip_connection: False
full_module_test_mode: False
early_stop_patience: 10
early_stop_delta: 0.0


# model, dataset and preprocess options
model: TCLNET_STAGE1
# model: ADVANCED_TCLNET
dataset_mode: heatmap
dataroot: /home/littlered/Documents/Improved-TCLNet/datasets/data/TCLDwithTSsame
img_size: 224
crop_scale: 1.12
flip: True
norm_type: standard


# non-model specific & basic configs
checkpoints_dir: checkpointsTCLNet
results_dir: testing_simam
save_epoch_freq: 1
init_type: normal
init_gain: 0.02
lr_policy: step
print_freq: 20
num_threads: 4
verbose: False





